---

- name: join manager nodes to cluster
  shell: >
    docker swarm join
    --advertise-addr={{ swarm_iface | default('eth0') }}:2377
    --token={{ token }}
    {{ groups['swarm_manager_ips'][0] }}:2377
