---
- hosts: all
  become: yes
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  roles:
    - patchOS
    - reboot-server
    - docker-ce
    - { role: REX-ray,
        rexray_service: true,
        rexray_storage_drivers: [virtualbox],
        rexray_vbox_volume_path: '"{{ playbook_dir }}/../Volumes"',
        rexray_vbox_endpoint: "http://10.0.2.2:18083",
        rexray_vbox_controller_name: SATA }
    - reboot-server


- hosts: manager
  become: true
  roles:
    - swarm-manager


- hosts: swarm_manager_bootstrap[0]
  become: true
  vars:
    swarm_iface: 'enp0s8'
  roles:
    - swarm-manager-bootstrap


- hosts: swarm_manager_operational[0]
  become: true
  vars:
    swarm_iface: 'enp0s8'
    iface: "{{ swarm_iface | default('eth0') }}"
  roles:
    - swarm-manager-operational


- hosts: swarm_manager_bootstrap:!swarm_manager_operational
  become: true
  vars:
    swarm_iface: 'enp0s8'
    token: "{{ hostvars[groups['swarm_manager_operational'][0]]['swarm_manager_token']['stdout'] }}"
  roles:
    - swarm-manager-join


- hosts: worker
  become: true
  roles:
    - swarm-worker


- hosts: swarm_worker_bootstrap
  become: true
  vars:
    swarm_iface: 'enp0s8'
    token: "{{ hostvars[groups['swarm_manager_operational'][0]]['swarm_worker_token']['stdout'] }}"
  roles:
    - swarm-worker-bootstrap

